timeout: 1200s
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/kubemacs:${TAG_NAME}'
      - '--build-arg'
      - 'IMAGE_ARG=gcr.io/${PROJECT_ID}/kubemacs:${TAG_NAME}'
      - '.'
images:
  - 'gcr.io/${PROJECT_ID}/kubemacs:${TAG_NAME}'
    # env:
    # - 'TAG=$TAG_NAME'
    # - 'REV=$REVISION_ID'
    # args: ['build', '-t', 'gcr.io/$PROJECT_ID/iimacs:$_GIT_TAG',
    #        '--build-arg', 'IMAGE_ARG=gcr.io/$PROJECT_ID/iimacs:$_GIT_TAG',
    #        '.']
    # dir: .
    # dir: apps/auditlogger
# substitutions:
#   _GIT_TAG: '12345'
# substitutions:
#   TAG_NAME: 'v0.9.3'
#   REVISION_ID: '0'
  # - 'gcr.io/$PROJECT_ID/iimacs:$_GIT_TAG'
